package com.jobhunting.platform.billing;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE,
        properties = "platform.billing.enabled=true")
@Testcontainers
@EnabledIfSystemProperty(named = "run.integration.tests", matches = "true")
class BillingServiceIntegrationTest {

    @Container
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine")
            .withDatabaseName("billing_test")
            .withUsername("billing_test")
            .withPassword("billing_test");

    @DynamicPropertySource
    static void databaseProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
    }

    @Autowired
    private BillingOperations billing;

    @Autowired
    private JdbcTemplate jdbc;

    @BeforeEach
    void resetDatabase() {
        // Keep the billing columns and uniqueness constraints aligned with the Python-owned tables.
        jdbc.execute("CREATE TABLE IF NOT EXISTS accounts (id integer PRIMARY KEY)");
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS account_balances (
                    account_id integer PRIMARY KEY REFERENCES accounts(id),
                    balance_micro_yuan bigint NOT NULL,
                    total_recharge_micro_yuan bigint NOT NULL DEFAULT 0,
                    total_consumed_micro_yuan bigint NOT NULL DEFAULT 0,
                    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS account_balance_ledger (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    account_id integer NOT NULL REFERENCES accounts(id),
                    entry_kind varchar(32) NOT NULL,
                    amount_micro_yuan bigint NOT NULL,
                    balance_before_micro_yuan bigint NOT NULL,
                    balance_after_micro_yuan bigint NOT NULL,
                    token_count integer,
                    price_per_million_tokens_yuan numeric(12, 6),
                    source_reference varchar(160) UNIQUE,
                    summary text NOT NULL,
                    details_json jsonb NOT NULL DEFAULT '{}'::jsonb,
                    created_at timestamptz NOT NULL
                )
                """);
        jdbc.execute("TRUNCATE account_balance_ledger, account_balances, accounts RESTART IDENTITY CASCADE");
        jdbc.update("INSERT INTO accounts (id) VALUES (42), (43)");
        jdbc.update("""
                INSERT INTO account_balances (account_id, balance_micro_yuan, total_recharge_micro_yuan)
                VALUES (42, 10000000, 10000000), (43, 10000000, 10000000)
                """);
    }

    @Test
    void chargeAndRetryCreateOneLedgerEntry() {
        var request = request(42, 2_000_000, "call-charge-once");

        var applied = billing.consume(request, request.source_reference());
        var replayed = billing.consume(request, request.source_reference());
        var balance = billing.getBalance(42);

        assertThat(applied.replayed()).isFalse();
        assertThat(replayed.replayed()).isTrue();
        assertThat(replayed.ledger_entry_id()).isEqualTo(applied.ledger_entry_id());
        assertThat(balance.balance_micro_yuan()).isEqualTo(8_000_000);
        assertThat(balance.total_consumed_micro_yuan()).isEqualTo(2_000_000);
        assertThat(balance.ledger_entry_count()).isEqualTo(1);
        assertThat(jdbc.queryForObject(
                "SELECT amount_micro_yuan FROM account_balance_ledger WHERE id = ?",
                Long.class,
                applied.ledger_entry_id())).isEqualTo(-2_000_000);
    }

    @Test
    void insufficientBalanceDoesNotChangeBalanceOrLedger() {
        var request = request(42, 11_000_000, "call-insufficient");

        assertThatThrownBy(() -> billing.consume(request, request.source_reference()))
                .isInstanceOf(BillingException.class)
                .extracting("code")
                .isEqualTo("INSUFFICIENT_BALANCE");
        assertThat(billing.getBalance(42).balance_micro_yuan()).isEqualTo(10_000_000);
        assertThat(billing.getBalance(42).ledger_entry_count()).isZero();
    }

    @Test
    void reusedKeyWithAnotherAmountIsRejectedWithoutChangingBalance() {
        billing.consume(request(42, 2_000_000, "call-conflict"), "call-conflict");

        assertThatThrownBy(() -> billing.consume(request(42, 3_000_000, "call-conflict"), "call-conflict"))
                .isInstanceOf(BillingException.class)
                .extracting("code")
                .isEqualTo("IDEMPOTENCY_CONFLICT");
        assertThat(billing.getBalance(42).balance_micro_yuan()).isEqualTo(8_000_000);
        assertThat(billing.getBalance(42).ledger_entry_count()).isEqualTo(1);
    }

    @Test
    void concurrentRetriesChargeOnlyOnce() throws Exception {
        var request = request(42, 7_000_000, "call-concurrent-retry");
        List<BillingDtos.ChargeResponse> responses = runTogether(
                () -> billing.consume(request, request.source_reference()),
                () -> billing.consume(request, request.source_reference()));

        assertThat(responses).filteredOn(BillingDtos.ChargeResponse::replayed).hasSize(1);
        assertThat(responses).filteredOn(response -> !response.replayed()).hasSize(1);
        assertThat(responses.get(0).ledger_entry_id()).isEqualTo(responses.get(1).ledger_entry_id());
        assertThat(billing.getBalance(42).balance_micro_yuan()).isEqualTo(3_000_000);
        assertThat(billing.getBalance(42).ledger_entry_count()).isEqualTo(1);
    }

    @Test
    void concurrentDifferentChargesCannotOverdraw() throws Exception {
        var first = request(42, 7_000_000, "call-concurrent-a");
        var second = request(42, 7_000_000, "call-concurrent-b");
        List<String> outcomes = runTogether(
                () -> consumeOutcome(first),
                () -> consumeOutcome(second));

        assertThat(outcomes).containsExactlyInAnyOrder("charged", "INSUFFICIENT_BALANCE");
        assertThat(billing.getBalance(42).balance_micro_yuan()).isEqualTo(3_000_000);
        assertThat(billing.getBalance(42).total_consumed_micro_yuan()).isEqualTo(7_000_000);
        assertThat(billing.getBalance(42).ledger_entry_count()).isEqualTo(1);
    }

    private String consumeOutcome(BillingDtos.ConsumeRequest request) {
        try {
            billing.consume(request, request.source_reference());
            return "charged";
        } catch (BillingException exception) {
            return exception.code();
        }
    }

    private BillingDtos.ConsumeRequest request(long accountId, long amount, String reference) {
        return new BillingDtos.ConsumeRequest(accountId, amount, 100L, reference, "test charge");
    }

    private <T> List<T> runTogether(Callable<T> first, Callable<T> second) throws Exception {
        ExecutorService executor = Executors.newFixedThreadPool(2);
        CountDownLatch start = new CountDownLatch(1);
        try {
            Future<T> firstResult = executor.submit(() -> {
                start.await();
                return first.call();
            });
            Future<T> secondResult = executor.submit(() -> {
                start.await();
                return second.call();
            });
            start.countDown();
            return List.of(firstResult.get(20, TimeUnit.SECONDS), secondResult.get(20, TimeUnit.SECONDS));
        } finally {
            executor.shutdownNow();
        }
    }
}
